# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1

    working_directory: ~/rail-uk

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements-dev.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: Install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements-dev.txt

    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

    # Run tests!
    - run:
        name: Run Unit Tests
        command: |
          . venv/bin/activate
          mkdir test-reports
          python3 -m pytest --cov-report term-missing --junitxml=test-reports/unit/junit.xml --cov=rail_uk
          codecov

    - run:
        name: Run End-to-End Tests
        command: |
          . venv/bin/activate
          python3 -m pytest tests/end_to_end_tests.py --junitxml=test-reports/end-to-end/junit.xml

    - store_test_results:
        path: test-reports
